# Generated: 2025-11-14T09:43:44.090522
# Generator: ANCRDT Transformation (AST-based)
# File: ancrdt_output_tables.py
# DO NOT EDIT THIS FILE DIRECTLY - Edit via web UI to preserve changes

from pybirdai.process_steps.pybird.orchestration import Orchestration
from pybirdai.process_steps.pybird.csv_converter import CSVConverter
from datetime import datetime
from pybirdai.annotations.decorators import lineage, track_table_init
from .ANCRDT_INSTRMNT_C_1_logic import *

class ANCRDT_INSTRMNT_C_1:
    unionOfLayers = None

    @lineage(dependencies={'unionOfLayers.RCRS'})
    def RCRS(self) -> str:
        return self.unionOfLayers.RCRS()

    @lineage(dependencies={'unionOfLayers.PRPS'})
    def PRPS(self) -> str:
        return self.unionOfLayers.PRPS()

    @lineage(dependencies={'unionOfLayers.FDCRY'})
    def FDCRY(self) -> str:
        return self.unionOfLayers.FDCRY()

    @lineage(dependencies={'unionOfLayers.RFRNC_RT'})
    def RFRNC_RT(self) -> str:
        return self.unionOfLayers.RFRNC_RT()

    @lineage(dependencies={'unionOfLayers.DT_RFRNC'})
    def DT_RFRNC(self) -> datetime:
        return self.unionOfLayers.DT_RFRNC()

    @lineage(dependencies={'unionOfLayers.CNTRCT_ID'})
    def CNTRCT_ID(self) -> str:
        return self.unionOfLayers.CNTRCT_ID()

    @lineage(dependencies={'unionOfLayers.DT_INCPTN'})
    def DT_INCPTN(self) -> datetime:
        return self.unionOfLayers.DT_INCPTN()

    @lineage(dependencies={'unionOfLayers.DT_STTLMNT'})
    def DT_STTLMNT(self) -> datetime:
        return self.unionOfLayers.DT_STTLMNT()

    @lineage(dependencies={'unionOfLayers.TYP_AMRTSTN'})
    def TYP_AMRTSTN(self) -> str:
        return self.unionOfLayers.TYP_AMRTSTN()

    @lineage(dependencies={'unionOfLayers.INSTRMNT_ID'})
    def INSTRMNT_ID(self) -> str:
        return self.unionOfLayers.INSTRMNT_ID()

    @lineage(dependencies={'unionOfLayers.SBRDNTD_DBT'})
    def SBRDNTD_DBT(self) -> str:
        return self.unionOfLayers.SBRDNTD_DBT()

    @lineage(dependencies={'unionOfLayers.INTRST_RT_CP'})
    def INTRST_RT_CP(self) -> float:
        return self.unionOfLayers.INTRST_RT_CP()

    @lineage(dependencies={'unionOfLayers.RPYMNT_RGHTS'})
    def RPYMNT_RGHTS(self) -> str:
        return self.unionOfLayers.RPYMNT_RGHTS()

    @lineage(dependencies={'unionOfLayers.INSTRMNT_TYP_PRDCT'})
    def INSTRMNT_TYP_PRDCT(self) -> str:
        return self.unionOfLayers.TYP_INSTRMNT()

    @lineage(dependencies={'unionOfLayers.PYMNT_FRQNCY'})
    def PYMNT_FRQNCY(self) -> str:
        return self.unionOfLayers.PYMNT_FRQNCY()


    @lineage(dependencies={'unionOfLayers.TYP_INTRST_RT'})
    def TYP_INTRST_RT(self) -> str:
        return self.unionOfLayers.TYP_INTRST_RT()

    @lineage(dependencies={'unionOfLayers.CRRNCY_DNMNTN'})
    def CRRNCY_DNMNTN(self) -> str:
        return self.unionOfLayers.CRRNCY_DNMNTN()

    @lineage(dependencies={'unionOfLayers.INTRST_RT_FLR'})
    def INTRST_RT_FLR(self) -> float:
        return self.unionOfLayers.INTRST_RT_FLR()

    @lineage(dependencies={'unionOfLayers.OBSRVD_AGNT_CD'})
    def OBSRVD_AGNT_CD(self) -> str:
        return self.unionOfLayers.OBSRVD_AGNT_CD()

    @lineage(dependencies={'unionOfLayers.INTRST_RT_SPRD'})
    def INTRST_RT_SPRD(self) -> float:
        return self.unionOfLayers.INTRST_RT_SPRD()

    @lineage(dependencies={'unionOfLayers.CMMTMNT_INCPTN'})
    def CMMTMNT_INCPTN(self) -> int:
        return self.unionOfLayers.CMMTMNT_INCPTN()

    @lineage(dependencies={'unionOfLayers.DT_LGL_FNL_MTRTY'})
    def DT_LGL_FNL_MTRTY(self) -> datetime:
        return self.unionOfLayers.DT_LGL_FNL_MTRTY()

    @lineage(dependencies={'unionOfLayers.SYNDCTD_CNTRCT_ID'})
    def SYNDCTD_CNTRCT_ID(self) -> str:
        return self.unionOfLayers.SYNDCTD_CNTRCT_ID()

    @lineage(dependencies={'unionOfLayers.DT_END_INTRST_ONLY'})
    def DT_END_INTRST_ONLY(self) -> datetime:
        return self.unionOfLayers.DT_END_INTRST_ONLY()

    @lineage(dependencies={'unionOfLayers.INTRST_RT_RST_FRQNCY'})
    def INTRST_RT_RST_FRQNCY(self) -> str:
        return self.unionOfLayers.INTRST_RT_RST_FRQNCY()

    @lineage(dependencies={'unionOfLayers.FV_CHNG_CR_BFR_PRCHS'})
    def FV_CHNG_CR_BFR_PRCHS(self) -> int:
        return self.unionOfLayers.FV_CHNG_CR_BFR_PRCHS()

class ANCRDT_INSTRMNT_C_1_Table:
    ANCRDT_INSTRMNT_C_1_UnionTable = None
    ANCRDT_INSTRMNT_C_1s = []

    def calc_ANCRDT_INSTRMNT_C_1s(self) -> list[ANCRDT_INSTRMNT_C_1]:
        items = []
        for item in self.ANCRDT_INSTRMNT_C_1_UnionTable.ANCRDT_INSTRMNT_C_1_UnionItems:
            newItem = ANCRDT_INSTRMNT_C_1()
            newItem.unionOfLayers = item
            items.append(newItem)
        return items

    @track_table_init
    def init(self):
        Orchestration().init(self)
        self.ANCRDT_INSTRMNT_C_1s = []
        self.ANCRDT_INSTRMNT_C_1s.extend(self.calc_ANCRDT_INSTRMNT_C_1s())
        CSVConverter.persist_object_as_csv(self, True)
        return None